# Generated by Django 5.0.6 on 2025-11-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_favorite_options_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
